import { StyleSheet } from 'react-native';
import { COLORS, FONT_SIZE, SPACING } from '../../Constants/theme';

const RADIUS_LG = 20;
const RADIUS_MD = 12;
const RADIUS_PILL = 22;

export default StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: COLORS.BACKGROUND,
  },
  headerShell: {
    backgroundColor: COLORS.PRIMARY,
    borderBottomLeftRadius: RADIUS_LG,
    borderBottomRightRadius: RADIUS_LG,
    overflow: 'hidden',
  },
  headerSafe: {
    backgroundColor: COLORS.PRIMARY,
  },
  bodyFlex: {
    flex: 1,
    minHeight: 0,
  },
  bodySurface: {
    backgroundColor: COLORS.BACKGROUND,
  },
  bodyInner: {
    flex: 1,
    minHeight: 0,
    paddingHorizontal: SPACING.MD,
    paddingTop: SPACING.SM,
  },
  dashboardColumn: {
    flex: 1,
    minHeight: 0,
    justifyContent: 'flex-start',
  },
  stackBackRow: {
    paddingHorizontal: SPACING.MD,
    paddingTop: SPACING.SM,
    paddingBottom: SPACING.XS,
  },
  stackBackText: {
    color: COLORS.PRIMARY,
    fontSize: FONT_SIZE.MD,
    fontWeight: '600',
  },
  hero: {
    marginTop: SPACING.XS,
    backgroundColor: COLORS.WHITE,
    borderRadius: RADIUS_MD,
    borderWidth: 1,
    borderColor: COLORS.CARD_BORDER,
    padding: SPACING.MD,
    paddingBottom: SPACING.MD,
    flexShrink: 0,
  },
  heroCompact: {
    marginTop: 0,
    padding: SPACING.SM,
    paddingBottom: SPACING.SM,
  },
  heroTitle: {
    color: COLORS.TEXT_PRIMARY,
    fontSize: FONT_SIZE.XXL,
    fontWeight: '700',
  },
  heroTitleCompact: {
    fontSize: FONT_SIZE.XL,
  },
  heroSubtitle: {
    color: COLORS.TEXT_SECONDARY,
    fontSize: FONT_SIZE.MD,
    lineHeight: 22,
    marginTop: SPACING.SM,
  },
  heroSubtitleCompact: {
    fontSize: FONT_SIZE.SM,
    lineHeight: 18,
    marginTop: SPACING.XS,
  },
  ctaButton: {
    marginTop: SPACING.MD,
    backgroundColor: COLORS.PRIMARY,
    paddingVertical: 15,
    paddingHorizontal: SPACING.LG,
    borderRadius: RADIUS_PILL,
    alignItems: 'center',
  },
  ctaButtonCompact: {
    marginTop: SPACING.SM,
    paddingVertical: SPACING.SM,
    paddingHorizontal: SPACING.MD,
  },
  ctaButtonText: {
    color: COLORS.WHITE,
    fontSize: FONT_SIZE.MD,
    fontWeight: '600',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginTop: SPACING.MD,
    marginBottom: SPACING.SM,
    flexShrink: 0,
  },
  sectionHeaderCompact: {
    marginTop: SPACING.SM,
    marginBottom: SPACING.XS,
  },
  sectionHeaderTextWrap: {
    flex: 1,
    minWidth: 0,
    marginRight: SPACING.SM,
  },
  sectionTitle: {
    color: COLORS.TEXT_PRIMARY,
    fontSize: FONT_SIZE.LG,
    fontWeight: '700',
  },
  sectionTagline: {
    color: COLORS.TEXT_SECONDARY,
    fontSize: FONT_SIZE.SM,
    marginTop: SPACING.XS,
    maxWidth: 320,
  },
  sectionTaglineCompact: {
    fontSize: 12,
    lineHeight: 16,
  },
  sectionAction: {
    color: COLORS.PRIMARY,
    fontSize: FONT_SIZE.SM,
    fontWeight: '600',
  },
  deviceList: {
    flex: 1,
    minHeight: 0,
    gap: SPACING.SM,
    justifyContent: 'flex-start',
  },
  deviceCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.WHITE,
    borderRadius: RADIUS_MD,
    padding: SPACING.MD,
    borderWidth: 1,
    borderColor: COLORS.CARD_BORDER,
  },
  deviceCardCompact: {
    paddingVertical: SPACING.SM,
    paddingHorizontal: SPACING.SM,
  },
  deviceCardActive: {
    borderColor: COLORS.CARD_SELECTED_BORDER,
    backgroundColor: COLORS.CARD_SELECTED_BG,
  },
  deviceIcon: {
    fontSize: 28,
    marginRight: SPACING.SM,
  },
  deviceCopy: {
    flex: 1,
    minWidth: 0,
  },
  deviceName: {
    color: COLORS.TEXT_PRIMARY,
    fontSize: FONT_SIZE.MD,
    fontWeight: '600',
  },
  deviceSubtitle: {
    color: COLORS.TEXT_SECONDARY,
    fontSize: FONT_SIZE.SM,
    marginTop: SPACING.XS,
  },
  deviceBadge: {
    backgroundColor: COLORS.CARD_SELECTED_BG,
    paddingHorizontal: SPACING.SM,
    paddingVertical: SPACING.XS,
    borderRadius: RADIUS_PILL,
    borderWidth: 1,
    borderColor: COLORS.CARD_BORDER,
  },
  deviceBadgeText: {
    color: COLORS.PRIMARY,
    fontSize: 11,
    fontWeight: '600',
  },
  deviceScreenHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: SPACING.MD,
    paddingVertical: SPACING.SM,
  },
  backButton: {
    paddingVertical: SPACING.SM,
    paddingRight: SPACING.SM,
  },
  backButtonText: {
    color: COLORS.PRIMARY,
    fontSize: FONT_SIZE.MD,
    fontWeight: '600',
  },
  backButtonPlaceholder: {
    width: 72,
  },
  deviceScreenTitle: {
    flex: 1,
    color: COLORS.TEXT_PRIMARY,
    fontSize: FONT_SIZE.LG,
    fontWeight: '700',
    textAlign: 'center',
  },
  deviceDetailWrap: {
    flex: 1,
    minHeight: 0,
    justifyContent: 'flex-start',
    paddingBottom: SPACING.XS,
  },
  deviceDetailHeading: {
    marginBottom: SPACING.SM,
  },
  deviceDetailTitle: {
    color: COLORS.TEXT_PRIMARY,
    fontSize: FONT_SIZE.XL,
    fontWeight: '700',
  },
  deviceDetailType: {
    color: COLORS.PRIMARY,
    fontSize: FONT_SIZE.SM,
    fontWeight: '600',
    marginTop: SPACING.XS,
  },
  deviceDetailBody: {
    color: COLORS.TEXT_SECONDARY,
    fontSize: FONT_SIZE.MD,
    lineHeight: 22,
    flexShrink: 1,
  },
  metrics: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.SM,
    marginTop: SPACING.SM,
    flexShrink: 0,
  },
  metricCard: {
    backgroundColor: COLORS.WHITE,
    borderRadius: RADIUS_MD,
    padding: SPACING.SM,
    minWidth: '28%',
    flexGrow: 1,
    flexBasis: 0,
    borderWidth: 1,
    borderColor: COLORS.CARD_BORDER,
  },
  metricLabel: {
    color: COLORS.TEXT_SECONDARY,
    fontSize: FONT_SIZE.SM,
    fontWeight: '600',
  },
  metricValue: {
    color: COLORS.TEXT_PRIMARY,
    fontSize: FONT_SIZE.LG,
    fontWeight: '700',
    marginTop: SPACING.XS,
  },
  connectButton: {
    marginTop: SPACING.MD,
    backgroundColor: COLORS.PRIMARY,
    paddingVertical: SPACING.SM,
    borderRadius: RADIUS_PILL,
    alignItems: 'center',
  },
  connectButtonDisabled: {
    opacity: 0.55,
  },
  connectButtonText: {
    color: COLORS.WHITE,
    fontSize: FONT_SIZE.MD,
    fontWeight: '600',
  },
  helpText: {
    color: COLORS.TEXT_MUTED,
    fontSize: FONT_SIZE.SM,
    lineHeight: 18,
    marginTop: SPACING.XS,
    textAlign: 'center',
    flexShrink: 0,
  },
  statusCard: {
    marginTop: SPACING.SM,
    backgroundColor: COLORS.WHITE,
    borderRadius: RADIUS_MD,
    padding: SPACING.SM,
    borderWidth: 1,
    borderColor: COLORS.CARD_BORDER,
    flexShrink: 1,
    minHeight: 0,
  },
  statusLabel: {
    color: COLORS.TEXT_SECONDARY,
    fontSize: FONT_SIZE.SM,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  statusValue: {
    color: COLORS.TEXT_PRIMARY,
    fontSize: FONT_SIZE.MD,
    fontWeight: '600',
    marginTop: SPACING.XS,
  },
  statusLine: {
    color: COLORS.TEXT_SECONDARY,
    fontSize: 12,
    marginTop: 2,
  },
  oximeterScreenBase: {
    flex: 1,
    backgroundColor: '#0c162a',
  },
  oximeterScreen: {
    flex: 1,
  },
  oximeterHero: {
    alignItems: 'center',
    marginBottom: 20,
  },
  oximeterLabel: {
    color: '#7dd3fc',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 16,
  },
  oximeterDeviceWrap: {
    alignItems: 'center',
  },
  oximeterDeviceShell: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#152238',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#38bdf8',
  },
  oximeterWave: {
    width: 72,
    height: 36,
    borderRadius: 8,
    backgroundColor: 'rgba(56, 189, 248, 0.35)',
  },
  oximeterMetrics: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 20,
  },
  oximeterMetricsStacked: {
    flexDirection: 'column',
  },
  oximeterMetricStackedSpacing: {
    marginTop: 12,
    marginLeft: 0,
  },
  oximeterMetricCard: {
    flex: 1,
    backgroundColor: '#152238',
    borderRadius: 14,
    padding: 16,
    minWidth: 0,
  },
  oximeterMetricPrimary: {
    borderWidth: 1,
    borderColor: 'rgba(56, 189, 248, 0.4)',
  },
  oximeterMetricLabel: {
    color: '#94a3b8',
    fontSize: 12,
    fontWeight: '600',
  },
  oximeterMetricValue: {
    color: '#f8fafc',
    fontSize: 32,
    fontWeight: '700',
    marginTop: 8,
  },
  oximeterMetricUnit: {
    color: '#64748b',
    fontSize: 12,
    marginTop: 4,
  },
  oximeterSetupCard: {
    backgroundColor: '#152238',
    borderRadius: 20,
    marginHorizontal: 16,
    marginVertical: 12,
  },
  oximeterSetupHeader: {
    alignItems: 'center',
    paddingTop: 20,
  },
  oximeterBody: {
    paddingTop: 8,
  },
  oximeterTitle: {
    color: '#f8fafc',
    fontSize: 22,
    fontWeight: '700',
    marginBottom: 12,
  },
  oximeterCopy: {
    color: '#94a3b8',
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 20,
  },
  oximeterConnectButton: {
    backgroundColor: '#38bdf8',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
  },
  oximeterConnectButtonText: {
    color: '#0c162a',
    fontSize: 16,
    fontWeight: '700',
  },

  /** Light-theme pulse oximeter flow (pair + live) */
  oxLightRoot: {
    flex: 1,
    minHeight: 0,
    backgroundColor: COLORS.WHITE,
    justifyContent: 'space-between',
  },
  oxLightHeader: {
    backgroundColor: COLORS.PRIMARY,
    paddingHorizontal: SPACING.MD,
    paddingBottom: SPACING.LG,
    borderBottomLeftRadius: RADIUS_LG,
    borderBottomRightRadius: RADIUS_LG,
  },
  oxLightHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  oxLightBackBtn: {
    paddingVertical: 10,
    paddingRight: 12,
    minWidth: 44,
  },
  oxLightBackText: {
    color: COLORS.WHITE,
    fontSize: 22,
    fontWeight: '600',
  },
  oxLightHeaderTitle: {
    flex: 1,
    color: COLORS.WHITE,
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
  },
  oxLightHeaderSpacer: {
    minWidth: 44,
  },
  oxLightImageWrap: {
    flex: 1,
    minHeight: 0,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: SPACING.SM,
  },
  oxLightHeroImage: {
    width: '100%',
    maxWidth: 340,
    aspectRatio: 0.85,
  },
  oxLightBottomCard: {
    flexShrink: 0,
    marginHorizontal: SPACING.MD,
    marginBottom: SPACING.SM,
    marginTop: SPACING.XS,
    backgroundColor: COLORS.WHITE,
    borderRadius: RADIUS_MD,
    paddingHorizontal: SPACING.LG,
    paddingTop: SPACING.MD,
    paddingBottom: SPACING.MD,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 1,
    borderColor: COLORS.CARD_BORDER,
  },
  oxLightBottomCardCompact: {
    paddingTop: SPACING.SM,
    paddingBottom: SPACING.SM,
    paddingHorizontal: SPACING.MD,
    marginBottom: SPACING.XS,
  },
  oxLightCardTitle: {
    color: COLORS.TEXT_PRIMARY,
    fontSize: FONT_SIZE.XL,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: SPACING.SM,
  },
  oxLightCardTitleCompact: {
    fontSize: FONT_SIZE.LG,
    marginBottom: SPACING.XS,
  },
  oxLightCardCopy: {
    color: COLORS.TEXT_SECONDARY,
    fontSize: FONT_SIZE.MD,
    lineHeight: 22,
    textAlign: 'center',
    marginBottom: SPACING.MD,
  },
  oxLightCardCopyCompact: {
    fontSize: FONT_SIZE.SM,
    lineHeight: 18,
    marginBottom: SPACING.SM,
  },
  oxLightPrimaryBtn: {
    backgroundColor: COLORS.PRIMARY,
    paddingVertical: SPACING.MD,
    borderRadius: 999,
    alignItems: 'center',
  },
  oxLightPrimaryBtnDisabled: {
    opacity: 0.55,
  },
  oxLightPrimaryBtnText: {
    color: COLORS.WHITE,
    fontSize: 17,
    fontWeight: '700',
  },
  oxLiveCenter: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 32,
  },
  oxLiveLiveCenterWrap: {
    flex: 1,
    width: '100%',
    minHeight: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  oxLiveLiveCenterInner: {
    width: '100%',
    maxWidth: 480,
    alignSelf: 'center',
  },
  oxLiveConnectingText: {
    marginTop: SPACING.MD,
    color: COLORS.TEXT_SECONDARY,
    fontSize: FONT_SIZE.MD,
    textAlign: 'center',
    lineHeight: 24,
    maxWidth: 320,
  },
  oxLiveMetricsCard: {
    flexShrink: 0,
    marginHorizontal: SPACING.MD,
    marginBottom: SPACING.MD,
    marginTop: SPACING.XS,
    backgroundColor: COLORS.WHITE,
    borderRadius: RADIUS_LG,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 6,
    borderWidth: 1,
    borderColor: COLORS.CARD_BORDER,
  },
  oxLiveMetricsCardCompact: {
    marginBottom: SPACING.SM,
  },
  oxLiveMetricsRow: {
    flexDirection: 'row',
    minHeight: 112,
  },
  oxLiveMetricsRowCompact: {
    minHeight: 88,
  },
  oxLiveMetricHalf: {
    flex: 1,
    paddingVertical: 20,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  oxLiveMetricHalfCompact: {
    paddingVertical: 12,
    paddingHorizontal: 8,
  },
  oxLiveLightTop: {
    backgroundColor: COLORS.WHITE,
    paddingHorizontal: SPACING.MD,
    paddingTop: SPACING.MD,
    paddingBottom: SPACING.SM,
  },
  oxLiveLightTopCompact: {
    paddingHorizontal: SPACING.SM,
    paddingTop: SPACING.SM,
    paddingBottom: SPACING.XS,
  },
  oxLiveLightLabel: {
    color: '#0a0a0a',
    fontSize: FONT_SIZE.MD,
    fontWeight: '700',
  },
  oxLiveLightValue: {
    color: '#2E5BFF',
    fontSize: 42,
    fontWeight: '800',
    marginTop: SPACING.XS,
  },
  oxLiveLightValueCompact: {
    fontSize: 34,
  },
  oxLiveLightDivider: {
    width: 1,
    alignSelf: 'stretch',
    marginVertical: SPACING.SM,
    backgroundColor: 'rgba(0, 0, 0, 0.08)',
  },
  oxLiveLightWaveClip: {
    width: '100%',
    overflow: 'hidden',
    backgroundColor: COLORS.WHITE,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
  },
  oxLiveLightWaveScroll: {
    height: '100%',
  },
  oxLiveRasterTile: {
    position: 'relative',
    overflow: 'hidden',
  },
  oxLiveRasterLayer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    top: 0,
    justifyContent: 'flex-end',
  },
  oxLiveRasterBarRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-end',
    width: '100%',
    height: '100%',
  },
  oxLiveRasterBar: {
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    minHeight: 2,
  },
  /** Overlap columns slightly so vertical seams disappear (no react-native-svg on RN 0.84 Fabric). */
  oxLiveRasterBarOverlap: {
    marginHorizontal: -1.35,
  },
  oxLiveMetricIconRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  oxLiveMetricIconSpacing: {
    marginRight: 6,
  },
  oxLiveStatusFooter: {
    flexShrink: 0,
    paddingHorizontal: 20,
    paddingBottom: SPACING.SM,
    marginTop: SPACING.MD,
  },
  oxLiveStatusFooterCompact: {
    paddingBottom: SPACING.XS,
    paddingHorizontal: SPACING.MD,
  },
  oxLiveStatusText: {
    fontSize: FONT_SIZE.SM,
    color: COLORS.TEXT_SECONDARY,
    textAlign: 'center',
  },
  oxLiveStatusTextError: {
    color: COLORS.ERROR,
  },
});
